http_server:
  port: 8080
  host: 127.0.0.1
database:
  store_type: memory
  database_url: postgresql://postgres:Password123@127.0.0.1:5432/moviedb?sslmode=disable
  log_level: Warn
  max_open_connections: 10
